apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-func
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-func
  template:
    metadata:
      labels:
        app: demo-func
    spec:
      containers:
      - name: demo-func
        image: slmcmahon/demo-func:v3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 80
        env:
        - name: TimerSchedule
          value: "0 0 1 * * *"
        - name: AzureWebJobsStorage
          value: "Put Your Storage Account Connection String Here"
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-func-scaledobject
spec:
  scaleTargetRef:
    name: demo-func
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cron
    metadata:
      timezone: "UTC"
      start: "0 0 * * *"
      end: "59 22 * * *"
      desiredReplicas: "1"
